# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:26
from __future__ import unicode_literals

import cf_users.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(default='', max_length=512, verbose_name='имя')),
                ('last_name', models.CharField(default='', max_length=512, verbose_name='фамилия')),
                ('middle_name', models.CharField(default='', max_length=512, verbose_name='отчество')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, verbose_name='номер телефона')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='согласие на подписку')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', cf_users.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.NullBooleanField(choices=[(None, 'Ожидает проверки'), (True, 'Разрешено'), (False, 'Отклонено')], default=None, verbose_name='статус модерации')),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='дата модерации')),
                ('process_status', models.CharField(blank=True, choices=[('', 'Ожидание'), ('CHECK', 'Отправлен на проверку'), ('APPLY', 'Применяется')], default='', max_length=8, verbose_name='статус обработки модерации')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=22, verbose_name='контактный номер телефона')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='контактный email')),
                ('title', models.CharField(blank=True, default='', max_length=512, verbose_name='название организации')),
                ('base_type', models.CharField(choices=[('REGULAR', 'Пользователь системы'), ('NCO', 'Некомерческая организация'), ('ORGANIZATION', 'ООО/ОАО')], default='REGULAR', max_length=32, verbose_name='тип профиля')),
                ('ref_points', models.IntegerField(default=0, help_text='баллы заработаные пользователем по реферальной системе', verbose_name='баллы реферальной системы')),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(default='', upload_to='', verbose_name='логотип')),
                ('notes', models.TextField(blank=True, default='', verbose_name='о себе')),
                ('web_link', models.URLField(blank=True, default='', verbose_name='сайт')),
                ('company_name', models.CharField(blank=True, default='', max_length=1048, verbose_name='название компании')),
                ('legal_address', models.TextField(blank=True, default='', verbose_name='юридический адрес')),
                ('postal_address', models.TextField(blank=True, default='', verbose_name='почтовый адрес')),
                ('tin', models.CharField(blank=True, default='', max_length=32, verbose_name='идентификационный номер налогоплательщика')),
                ('rrc', models.CharField(blank=True, default='', max_length=512, verbose_name='код причины регистрации')),
                ('rce', models.CharField(blank=True, default='', max_length=512, verbose_name='общероссийский классификатор предприятий и организаций')),
                ('rcg', models.CharField(blank=True, default='', max_length=512, verbose_name='общероссийский классификатор органов государственной власти и управления')),
                ('rco', models.CharField(blank=True, default='', max_length=512, verbose_name='общероссийский классификатор объектов административно-территориального деления')),
                ('okved', models.CharField(blank=True, default='', max_length=512, verbose_name='ОКВЭД')),
                ('rcf', models.CharField(blank=True, default='', max_length=512, verbose_name='общероссийский классификатор организационно-правовых форм')),
                ('lfb', models.CharField(blank=True, default='', max_length=512, verbose_name='организационно-правовые формы хозяйствующих субъектов')),
                ('name_bank', models.CharField(blank=True, default='', max_length=2048, verbose_name='наименование банка')),
                ('checking_account', models.CharField(blank=True, default='', max_length=512, verbose_name='рассчетный счет')),
                ('correspondent_account', models.CharField(blank=True, default='', max_length=512, verbose_name='корреспондентский счет')),
                ('bic', models.CharField(blank=True, default='', max_length=512, verbose_name='БИК банка')),
                ('head_full_name', models.CharField(blank=True, default='', max_length=1048, verbose_name='полное имя руководителя')),
                ('accountant_full_name', models.CharField(blank=True, default='', max_length=1048, verbose_name='ФИО бухгалтера')),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_granted_list', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
